### ISSUE TITLE
Page scroll block breaks Bynder scroll

### ISSUE THREAD

**Issue by JurgenvanF** [Bynder/bynder-js-sdk#125]
Hi there, question about the Bynder compact-view. Didn't know which repo to post this. I open the Bynder modal in a sidebar which blocks the scroll of the page itself on mount. Doing this also completely breaks the scroll in the Bynder modal giving lots of errors. So, blocking the scroll on the page breaks the scroll of Bynder.
<img width="633" alt="Schermafbeelding 2022-12-20 om 10 04 05" src="https://user-images.githubusercontent.com/70574217/208628375-4bd7acb4-c0a7-4dc2-809f-a1a75c63422d.png">

**Comment by TimBloembergen** [comment]
Hi @JurgenvanF ,

Compact View questions can be send to support@bynder.com. Our support team will be able to help you out and file a bug with the team owning UCV to look at it.

Thanks
