### ISSUE TITLE
dist directory missing with 1.1.0 release

### ISSUE THREAD

**Issue by rnsloan** [Bynder/bynder-js-sdk#17]
`@bynder/bynder-js-sdk@1.1.0` does not have a `dist` directory. 

`@bynder/bynder-js-sdk@1.0.4` is fine.

Can see it is missing in the distribution tarball: https://registry.npmjs.org/@bynder/bynder-js-sdk/-/bynder-js-sdk-1.1.0.tgz

prepublish failure?

**Comment by Calcyfer** [comment]
Confirmed, currently using a fork. Please update when it's fixed. :)

**Comment by danielsequeira** [comment]
Can you guys check again? Should be fixed with the new version 1.1.2 :)

**Comment by Calcyfer** [comment]
Fixed indeed! Thanks for the speedy fix!

**Comment by rnsloan** [comment]
Looks good, thanks.
