### ISSUE TITLE
Upload stream

### ISSUE THREAD

**Issue by Huljo** [Bynder/bynder-js-sdk#20]
Is it possible to use a stream as parameter of uploadFile ? 
Trying to stream files from AWS S3 (using AWS SDK) to a Bynder instance.

**Comment by danielsequeira** [comment]
Hey @Huljo. At the moment this is not possible, you can only upload using the file itself. @osener @GuilhermeSCP is this something we could have a look into?

**Comment by Huljo** [comment]
Hey @GuilhermeSCP
I didn't found any example about it so I tryed this way (based on uploadFile example [here](https://github.com/Bynder/bynder-js-sdk/blob/master/samples/upload.js)) :

````javascript
const fs = require('fs');
const path = require('path');
const Bynder = require('@bynder/bynder-js-sdk').default;
const bynderConfig = {
    consumer: {
        public: '********',
        secret: '********',
    },
    accessToken: {
        public: '********',
        secret: '********',
    },
    "baseURL": "https://********.getbynder.com/api/"
};

const bynder = new Bynder(bynderConfig);
bynder.getBrands()
    .then((data) => {
        const brand = data[0];
        const file = `${__dirname}/testasset.png`;
        return bynder.uploadFile({
            filename: path.basename(file),
            body: fs.createReadStream(file),
            data: {
                brandId: brand.id,
                name: 'test asset'
            }
        });
    })
    .then(console.log)
    .catch((error) => {
        console.error(error);
    });
````

It throw me an error related to the file length :
````
{ status: 0,
  message: 'The upload length is not valid or it was not specified properly' }
````

Where can I find the documentation about this method ?

Thank you guys for the support.

**Comment by GuilhermeSCP** [comment]
Just took a new look and you're right, that case is not entirely covered, I'll reopen and escalate the issue. Thanks for letting us know!

**Comment by Huljo** [comment]
I added a property length to uploadFile properties ( bynder.uploadFile({..., length:<int>, ...}) ). The upload is working now but I have to get the total file length before using uploadFile.

Not sure if it is uploading every stream chunks on the fly or if it's waiting the entire file to push chunk separately. (Since Im working on AWS Lambdas I cant work with FS so I need the first behavior)

**Comment by osener** [comment]
@Huljo thank you for the test case, you're absolutely right. We will release a fix as soon as possible.

Have a great weekend!

**Comment by osener** [comment]
@Huljo we've investigated possibilities for allowing this, but unfortunately our uploads API has to know the number of chunks ahead of time. I'm afraid we can't address this until Bynder gets a new API for uploads. We'll keep you posted if we hear about any plans for this.

For now, I suggest getting the length of your source file yourself. Since how to do this depends on the type of the stream, I don't think we'll implement this in the SDK. 

You mentioned you won't be using `fs`, but if you can read the file size via the `ContentLength` property of `S3.getObject` response or `content-length` response header of an HTTP stream it should do the trick.

Let us know if you have further questions.

**Comment by Huljo** [comment]
Thank you for the quick reply @osener .
Using `content-length` from `S3.getObject` do the trick for me. 

Everything looks ready to handle stream data using the SDK. There is just a lack of information about how to use it. Maybe you should plan to create an example using length property in uploadFile options or a short documentation.

**Comment by osener** [comment]
Noted :+1:. Happy to hear you got it working!
