### ISSUE TITLE
Upgrade to axios 0.19.0

### ISSUE THREAD

**Issue by jordanrastrick** [Bynder/bynder-js-sdk#24]
Hi - we've been using a resolution to force `bynder-js-sdk` to use `axios@0.19.0-beta.1` for a while (as we need it to enable tunnelling through our internal http proxy for https requests). Now that `axios@0.19.0` has been released, would it be possible to bump the version officially in the SDK? Cheers.

**Comment by danielsequeira** [comment]
Hey @jordanrastrick, yesterday we released a new version (v1.4.0) of the `bynder-js-sdk` that already uses `axios@0.19.0`.

**Comment by jordanrastrick** [comment]
Great, thanks so much 👍
