### ISSUE TITLE
Return Chunk Upload and Number of Chunk

### ISSUE THREAD

**Issue by JPBelley** [Bynder/bynder-js-sdk#38]
I want to create a progress bar since I'll be uploading big files.
Is there a way to have access to the number of chunk created. 
After that, is there a way to catch every response for each chunk to make my progress bar progress. I can't find a way at the moment. Thanks

**Comment by danielsequeira** [comment]
Hi @JPBelley,

No, at the moment we don't have this logic implemented in the SDK. The `uploadFile` function: https://github.com/Bynder/bynder-js-sdk/blob/master/src/bynder-js-sdk.js#L949 is responsible to call all the other functions that allows for a file to be uploaded to Bynder.

However this should be possible to achieve by creating a new function that has access to what is returned by the `uploadFileInChunks` function: https://github.com/Bynder/bynder-js-sdk/blob/master/src/bynder-js-sdk.js#L863.

We already do something similar in our Java SDK: https://github.com/Bynder/bynder-java-sdk/blob/master/src/main/java/com/bynder/sdk/service/upload/FileUploader.java#L104.

Feel free to create a pull request with these changes and we will have a look at it :)

**Comment by elseee** [comment]
Added in v2.3.9
