### ISSUE TITLE
uploadFile seems to be too slow

### ISSUE THREAD

**Issue by bernardodestefano** [Bynder/bynder-js-sdk#43]
Hello there,
i'm trying to upload some assets saved in a mongodb collection to bynder using the js-sdk.
For some reason each and every successful call takes 15 seconds to conclude which seems to be very strange. Is this expected?

I have the following code:

```javascript
uploadFile({
            filename: `SMCR_UGC_${submission.fileId}`,
            length: submission.fileSizeInBytes,
            body: fileStream,
            data: {
              brandId: submission.brandId,
              name: `SMCR_UGC_${submission.fileId}`,
              description: submission.description,
              ...languageMetaProperty,
              ...destinationMetaProperty,
              ...fileTypeMetaProperty,
              ...subFileTypeMetaProperty,
            },
})```

**Comment by danielsequeira** [comment]
Hi @bernardodestefano,

Yes unfortunately, our average to upload a file through our API is around 10 ~ 15 seconds. Of course this value varies, but it will always depend in a lot of factors, like how many uploads we are processing/converting at the moment, etc. If you are performing a mass upload in case it is possible I would recommend that you schedule it for after work hours, during the evening or even during the night.

Besides that can I ask you which values are you passing in the following variables:
```
...languageMetaProperty,
...destinationMetaProperty,
...fileTypeMetaProperty,
...subFileTypeMetaProperty,
```
I'm wondering if you might be passing some invalid data.

**Comment by bernardodestefano** [comment]
Hi @danielsequeira 
```javascript
languageMetaProperty['metaproperty.2023AAF3-7E00-4CAD-8E41D3835E496D68'] = '01E2253C-1888-4A38-90BDC140CBE7B5C8'

destinationMetaProperty['metaproperty.2009DAC5-52F9-4967-B1F689E2E1D57D0A'] = 'ed8dd2e6-b903-4876-b5f09954cbf84c19'

fileTypeMetaProperty['metaproperty.4AD1F80E-A6FB-4113-B4A1C606C88C6CDA'] =
        '19F6C6F0-E19F-4FF8-8763AE402727A5DA'

subFileTypeMetaProperty[
        `metaproperty.B7A06778-4EE5-4161-BDDBBFA5E60C3855`
      ] =
        'D7518778-3A79-4F94-8CDF34A654DE4615,19F6C6F0-E19F-4FF8-8763AE402727A5DA,8CD75CB3-21EC-448D-9259DD127786D686';
```

**Comment by danielsequeira** [comment]
Hi @bernardodestefano,

That looks fine. Besides the fact that this id `ed8dd2e6-b903-4876-b5f09954cbf84c19` is not in the CFUUID format.

**Comment by bernardodestefano** [comment]
![image](https://user-images.githubusercontent.com/17434488/70704644-b98da880-1cd2-11ea-8978-d9e20f7652f7.png)

Hi @danielsequeira that's the UID i got from the specific destination (Oxford) coming from bynder.getMetaProperties()

**Comment by danielsequeira** [comment]
true, but I'm wondering if passing the characters in lower case will still work as expected
