### ISSUE TITLE
v2.3.0 is not marked as latest release

### ISSUE THREAD

**Issue by okko** [Bynder/bynder-js-sdk#48]
https://github.com/Bynder/bynder-js-sdk/releases/tag/v2.3.0 is latest but not marked as latest. The new GitHub layout links to the 2nd-latest version instead:

<img width="307" alt="Screenshot 2020-06-26 at 12 01 10" src="https://user-images.githubusercontent.com/485375/85840216-cec8b100-b7a4-11ea-9746-cc6005dd78c4.png">

**Comment by betacar** [comment]
Fix with the latest releases.
