### ISSUE TITLE
Permanent tokens doesn't seem to work. 

### ISSUE THREAD

**Issue by zmitry** [Bynder/bynder-js-sdk#82]
Hi, I'm trying to follow guide from readme but permanent token doesn't seem to work. 
```
const Bynder = require('@bynder/bynder-js-sdk');

const bynder = new Bynder({
  baseURL: 'https://company.getbynder.com/api/',
  permanentToken: 'token',
});

bynder
  .getMediaList({
    type: 'image',
    limit: 9,
    page: 1,
  })
  .then(console.log, console.error);

```

**Comment by betacar** [comment]
Hi @zmitry! 
As per #68, permanent token support was dropped in favor of client credentials.

**Comment by zmitry** [comment]
@betacar could you provide example how to use your api with new approach?

**Comment by squamuglia** [comment]
@betacar  Can you update the readme to reflect that this is the case?

**Comment by rbndelrio** [comment]
@betacar 
> As per https://github.com/Bynder/bynder-js-sdk/pull/68, permanent token support was dropped in favor of client credentials.

Just flagging that this was never released, so permanent tokens are still part of the SDK and client credentials aren't yet supported.
